name: Test Flask server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask server
        run: python main.py &
        id: server

      - name: Wait for server to start
        run: sleep 5

      - name: Stop Flask server
        if: ${{ job.status == 'success' }}
        run: |
          if pgrep -f "python app.py" > /dev/null; then
            kill $(pgrep -f "python main.py")
          fi
