name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  mark-stale:
    runs-on: ubuntu-latest

    steps:
      - name: Mark stale issues and pull requests
        uses: peter-evans/stale@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because there has been no activity for 80 days. Please comment on this issue if you still need help or if the issue is still relevant.'
          stale-pr-message: 'This pull request has been automatically marked as stale because there has been no activity for 80 days. Please review and update this pull request if it is still relevant.'
          days-before-stale: 80
          days-before-close: 7

      - name: Add stale label to issues and pull requests
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const staleLabel = 'stale';
            const context = github.context;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { owner, repo } = context.repo;

            // Add the stale label to issues and pull requests
            const addLabel = async (number) => {
              await octokit.issues.addLabels({
                owner,
                repo,
                issue_number: number,
                labels: [staleLabel]
              });
            };

            // Remove the stale label from issues and pull requests
            const removeLabel = async (number) => {
              await octokit.issues.removeLabel({
                owner,
                repo,
                issue_number: number,
                name: staleLabel
              });
            };

            // Check if the event is an issue or pull request
            if (context.eventName === 'issues') {
              const { action, issue } = context.payload;
              const { number } = issue;

              // Add the stale label when an issue is opened or edited
              if (action === 'opened' || action === 'edited') {
                await addLabel(number);
              }

              // Remove the stale label when an issue is labeled or unlabeled
              if (action === 'labeled' || action === 'unlabeled') {
                await removeLabel(number);
              }
            }

            // Check if the event is a pull request
            if (context.eventName === 'pull_request') {
              const { action, pull_request } = context.payload;
              const { number } = pull_request;

              // Add the stale label when a pull request is opened or edited
              if (action === 'opened' || action === 'edited') {
                await addLabel(number);
              }

              // Remove the stale label when a pull request is labeled or unlabeled
              if (action === 'labeled' || action === 'unlabeled') {
                await removeLabel(number);
              }
            }
